// ================== bullets ==================
var BULLET_DAMAGE = 1;
var BULLET_SPEED = 9;
var BULLET_LIFETIME = 50;

var MACHINE_GUN_BULLET_DAMAGE = 2;
var MACHINE_GUN_BULLET_SPEED = 12;
var MACHINE_GUN_BULLET_LIFETIME = 50;

var ROCKET_DAMAGE = 10;
var ROCKET_START_SPEED = 2;
var ROCKET_LIFETIME = 100;
var ROCKET_ACCELERATION = 0.3;
var ROCKET_START_ACCELERATION_LIFETIME = 70;
var ROCKET_END_ACCELERATION_LIFETIME = 30;

var EXPLOSIVE_ROCKET_DAMAGE = 10;
var EXPLOSIVE_ROCKET_START_SPEED = 2;
var EXPLOSIVE_ROCKET_LIFETIME = 100;
var EXPLOSIVE_ROCKET_FRACTION_COUNT = 60;
var EXPLOSIVE_ROCKET_FRACTION_DAMAGE = 2;
var EXPLOSIVE_ROCKET_FRACTION_LIFETIME = 10;
// ==============================================

// ================== weapons ===================
var WEAPON_FRONT_LENGTH = 30;
var WEAPON_HARDNESS = 100;
var WEAPON_MAX_SECTOR = 20;

var AUTOMATIC_WEAPON_RATE_OF_FIRE = 300;

var MACHINE_GUN_FRONT_LENGTH = 35;
var MACHINE_GUN_HARDNESS = 1000;
var MACHINE_GUN_MAX_SECTOR = 30;
var MACHINE_GUN_RATE_OF_FIRE = 850;

var ROCKET_LAUNCHER_FRONT_LENGTH = 30;
var ROCKET_LAUNCHER_HARDNESS = 1000;
var ROCKET_LAUNCHER_MAX_SECTOR = 30;
// ==============================================

// ================== units =====================
var UNIT_HP = 10;
var UNIT_RADIUS = 20;
var UNIT_SPEED = 1;
var UNIT_WEAPON_OFFSET_Y = 15;

var PLAYER_HP = 10;
var PLAYER_SPEED = 3;
// ==============================================